name: cura_doctor
description: Cura Doctor Mobile App by Halo Group - Comprehensive Healthcare Management Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.1
  permission_handler: ^11.0.1
  webview_flutter: ^4.4.1
  url_launcher: ^6.1.12
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  video_player: ^2.7.2
  agora_rtc_engine: ^6.3.2
  path_provider: ^2.1.1
  flutter_pdfview: ^1.3.2
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700